version: '3.1'

services:
  app:
    image: 'e23f8b44c555'
    container_name: app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_URL=jdbc:postgresql://db:5432/postgres
    depends_on:
      - db

  db:
    image: 'postgres'
    container_name: db
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
